---

services:
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "bash", "-c", "rabbitmq-diagnostics check_port_connectivity && rabbitmq-diagnostics -q ping && rabbitmq-diagnostics -q check_running"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 15s

  api_gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "5000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@database:5432/ecommerce
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_CONNECTION_ATTEMPTS=10
      - RABBITMQ_RETRY_DELAY=5

  order_services:
    build:
      context: ./order_services
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@database:5432/ecommerce
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_CONNECTION_ATTEMPTS=10
      - RABBITMQ_RETRY_DELAY=5

  inventory_services:
    build:
      context: ./inventory_services
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@database:5432/ecommerce
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_CONNECTION_ATTEMPTS=10
      - RABBITMQ_RETRY_DELAY=5

  user_services:
    build:
      context: ./user_services
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@database:5432/ecommerce
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_CONNECTION_ATTEMPTS=10
      - RABBITMQ_RETRY_DELAY=5

volumes:
  postgres_data:
  pgadmin-data:
