---
services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    env_file:
      - .env

  database_service:
    build:
      context: .
      dockerfile: ./database_service/Dockerfile
    depends_on:
      - rabbitmq
      - db
    ports:
      - "${CRUD_PORT}:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}

  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "${GATEWAY_PORT}:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq/

  inventory_service:
    build:
      context: .
      dockerfile: ./inventory_service/Dockerfile
    depends_on:
      - rabbitmq
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq/


volumes:
  postgres_data:
